// Code generated by MockGen. DO NOT EDIT.
// Source: alu.go

// Package emu is a generated GoMock package.
package emu

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	vm "github.com/sarchlab/akita/v3/mem/vm"
	insts "github.com/sarchlab/mgpusim/v3/insts"
)

// MockInstEmuState is a mock of InstEmuState interface.
type MockInstEmuState struct {
	ctrl     *gomock.Controller
	recorder *MockInstEmuStateMockRecorder
}

// MockInstEmuStateMockRecorder is the mock recorder for MockInstEmuState.
type MockInstEmuStateMockRecorder struct {
	mock *MockInstEmuState
}

// NewMockInstEmuState creates a new mock instance.
func NewMockInstEmuState(ctrl *gomock.Controller) *MockInstEmuState {
	mock := &MockInstEmuState{ctrl: ctrl}
	mock.recorder = &MockInstEmuStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstEmuState) EXPECT() *MockInstEmuStateMockRecorder {
	return m.recorder
}

// Inst mocks base method.
func (m *MockInstEmuState) Inst() *insts.Inst {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inst")
	ret0, _ := ret[0].(*insts.Inst)
	return ret0
}

// Inst indicates an expected call of Inst.
func (mr *MockInstEmuStateMockRecorder) Inst() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inst", reflect.TypeOf((*MockInstEmuState)(nil).Inst))
}

// PID mocks base method.
func (m *MockInstEmuState) PID() vm.PID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PID")
	ret0, _ := ret[0].(vm.PID)
	return ret0
}

// PID indicates an expected call of PID.
func (mr *MockInstEmuStateMockRecorder) PID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PID", reflect.TypeOf((*MockInstEmuState)(nil).PID))
}

// ReadOperand mocks base method.
func (m *MockInstEmuState) ReadOperand(operand *insts.Operand, laneID int, buf []uint32) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOperand", operand, laneID, buf)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// ReadOperand indicates an expected call of ReadOperand.
func (mr *MockInstEmuStateMockRecorder) ReadOperand(operand, laneID, buf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOperand", reflect.TypeOf((*MockInstEmuState)(nil).ReadOperand), operand, laneID, buf)
}

// ReadReg mocks base method.
func (m *MockInstEmuState) ReadReg(reg *insts.Reg, regCount, laneID int) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadReg", reg, regCount, laneID)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// ReadReg indicates an expected call of ReadReg.
func (mr *MockInstEmuStateMockRecorder) ReadReg(reg, regCount, laneID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadReg", reflect.TypeOf((*MockInstEmuState)(nil).ReadReg), reg, regCount, laneID)
}

// ReadRegMore mocks base method.
func (m *MockInstEmuState) ReadRegMore(reg *insts.Reg, regCount, laneID int, buf []uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReadRegMore", reg, regCount, laneID, buf)
}

// ReadRegMore indicates an expected call of ReadRegMore.
func (mr *MockInstEmuStateMockRecorder) ReadRegMore(reg, regCount, laneID, buf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRegMore", reflect.TypeOf((*MockInstEmuState)(nil).ReadRegMore), reg, regCount, laneID, buf)
}

// WriteOperand mocks base method.
func (m *MockInstEmuState) WriteOperand(operand *insts.Operand, laneID int, data uint64, buf []uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteOperand", operand, laneID, data, buf)
}

// WriteOperand indicates an expected call of WriteOperand.
func (mr *MockInstEmuStateMockRecorder) WriteOperand(operand, laneID, data, buf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOperand", reflect.TypeOf((*MockInstEmuState)(nil).WriteOperand), operand, laneID, data, buf)
}

// WriteReg mocks base method.
func (m *MockInstEmuState) WriteReg(reg *insts.Reg, regCount, laneID int, data uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteReg", reg, regCount, laneID, data)
}

// WriteReg indicates an expected call of WriteReg.
func (mr *MockInstEmuStateMockRecorder) WriteReg(reg, regCount, laneID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteReg", reflect.TypeOf((*MockInstEmuState)(nil).WriteReg), reg, regCount, laneID, data)
}

// WriteRegMore mocks base method.
func (m *MockInstEmuState) WriteRegMore(reg *insts.Reg, regCount, laneID int, buf []uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteRegMore", reg, regCount, laneID, buf)
}

// WriteRegMore indicates an expected call of WriteRegMore.
func (mr *MockInstEmuStateMockRecorder) WriteRegMore(reg, regCount, laneID, buf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteRegMore", reflect.TypeOf((*MockInstEmuState)(nil).WriteRegMore), reg, regCount, laneID, buf)
}

// MockALU is a mock of ALU interface.
type MockALU struct {
	ctrl     *gomock.Controller
	recorder *MockALUMockRecorder
}

// MockALUMockRecorder is the mock recorder for MockALU.
type MockALUMockRecorder struct {
	mock *MockALU
}

// NewMockALU creates a new mock instance.
func NewMockALU(ctrl *gomock.Controller) *MockALU {
	mock := &MockALU{ctrl: ctrl}
	mock.recorder = &MockALUMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockALU) EXPECT() *MockALUMockRecorder {
	return m.recorder
}

// LDS mocks base method.
func (m *MockALU) LDS() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LDS")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// LDS indicates an expected call of LDS.
func (mr *MockALUMockRecorder) LDS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LDS", reflect.TypeOf((*MockALU)(nil).LDS))
}

// Run mocks base method.
func (m *MockALU) Run(state InstEmuState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", state)
}

// Run indicates an expected call of Run.
func (mr *MockALUMockRecorder) Run(state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockALU)(nil).Run), state)
}

// SetLDS mocks base method.
func (m *MockALU) SetLDS(lds []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLDS", lds)
}

// SetLDS indicates an expected call of SetLDS.
func (mr *MockALUMockRecorder) SetLDS(lds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLDS", reflect.TypeOf((*MockALU)(nil).SetLDS), lds)
}
